name: move_job
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_riverpod: ^2.5.1
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  http: ^1.2.1
  latlong2: ^0.9.1
  path_provider: ^2.1.3
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
